version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./backend/app:/app
    networks:
      - app_network
    depends_on:
      - db

  # Frontend Service
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - backend

  # Optional: Database Service (if needed)
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=document_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

# Networks
networks:
  app_network:
    driver: bridge

# Volumes
volumes:
  db_data:
